CREATE TABLE IF NOT EXISTS system_settings (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  uploads_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  maximum_upload_size_mb INTEGER NOT NULL DEFAULT 1024,
  allowed_upload_formats JSONB NOT NULL DEFAULT '["mp3","wav","m4a","aac","flac","ogg","mp4","mov","mkv","webm"]'::jsonb,
  require_reference_number BOOLEAN NOT NULL DEFAULT FALSE,
  require_category BOOLEAN NOT NULL DEFAULT TRUE,
  processing_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  automatic_processing BOOLEAN NOT NULL DEFAULT TRUE,
  automatic_analysis BOOLEAN NOT NULL DEFAULT FALSE,
  maximum_processing_retries INTEGER NOT NULL DEFAULT 3,
  retry_delay_minutes INTEGER NOT NULL DEFAULT 5,
  transcript_editing_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  speaker_renaming_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  transcript_downloads_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  enabled_download_formats JSONB NOT NULL DEFAULT '["txt","json","srt","vtt","pdf"]'::jsonb,
  require_approval_before_download BOOLEAN NOT NULL DEFAULT FALSE,
  analysis_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  enabled_analysis_outputs JSONB NOT NULL DEFAULT '["summary","keywords","entities","classification","english_translation"]'::jsonb,
  require_approval_before_analysis BOOLEAN NOT NULL DEFAULT FALSE,
  users_can_rerun_analysis BOOLEAN NOT NULL DEFAULT TRUE,
  cleanup_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  transcript_retention_days INTEGER NOT NULL DEFAULT 0,
  media_retention_days INTEGER NOT NULL DEFAULT 0,
  notification_retention_days INTEGER NOT NULL DEFAULT 90,
  audit_retention_days INTEGER NOT NULL DEFAULT 365,
  failed_upload_retention_days INTEGER NOT NULL DEFAULT 30,
  session_duration_minutes INTEGER NOT NULL DEFAULT 720,
  maximum_failed_login_attempts INTEGER NOT NULL DEFAULT 5,
  account_lockout_minutes INTEGER NOT NULL DEFAULT 15,
  notify_transcription_complete BOOLEAN NOT NULL DEFAULT TRUE,
  notify_processing_failed BOOLEAN NOT NULL DEFAULT TRUE,
  notify_analysis_complete BOOLEAN NOT NULL DEFAULT TRUE,
  notify_transcript_assigned BOOLEAN NOT NULL DEFAULT TRUE,
  notify_review_status_changed BOOLEAN NOT NULL DEFAULT TRUE,
  maintenance_mode BOOLEAN NOT NULL DEFAULT FALSE,
  maintenance_message TEXT,
  announcement_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  announcement_message TEXT,
  announcement_expires_at TIMESTAMPTZ,
  organisation_name TEXT,
  pdf_header_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by UUID REFERENCES users(id) ON DELETE SET NULL
);

INSERT INTO system_settings (id) VALUES (1)
ON CONFLICT (id) DO NOTHING;
